FROM csighub.tencentyun.com/opc-backend/golangbase-1.16:latest

COPY ./ /usr/local/services/ai-media/

ARG ffmpeg_enable=false

RUN if [ "$ffmpeg_enable" = "true" ]; then echo "enable ffmpeg "${ffmpeg_enable}; apk add ffmpeg; fi

RUN echo "export LANG=en_US.UTF-8" >> /etc/bashrc && echo "Asia/shanghai" >> /etc/timezone && echo "export CGO_ENABLED=0" >>  /etc/profile

WORKDIR /usr/local/services/ai-media/

CMD ["sh", "-c", "sleep infinity"]
